name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Run a multi-line script
      run: ls -lR
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./apis/poi/poi.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
